name: User API CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Set up MySQL Database
        run: |
          mysql -e "CREATE DATABASE userapi;"
          mysql -e "USE userapi;"
          mysql -e "GRANT ALL PRIVILEGES ON userapi.* TO 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: Run Tests
        run: npm test

      - name: Build and Deploy
        run: npm run build && npm run deploy
